Try to make entrypoint da script compatible with zsh.

diff --git a/da b/da
--- a/da
+++ b/da
@@ -59,20 +59,33 @@ set -o pipefail  # don't hide errors within pipes
 
 
 # -----------------------------------------------------------------------------
-# Check to ensure required commands exist.
+# Check to ensure that the environment is configured as required.
 #
 # This section uses 'command' to check that the
-# 'python3', 'pip3' and 'git' commands exist in
-# the current execution environment, and halt the
-# bash script with an error code and an error
-# message on stderr if any of them are missing.
+# 'python3', 'pip3', 'git'  and 'sshd' commands
+# exist in the current execution environment.
+#
+# It also checks for the presence of a public SSH
+# key in ~/.ssh/id_rsa.pub and that passwordless
+# SSH to localhost is configured.
+#
+# If any of these prerequisites are missing, the
+# bash script will be halted with an error code
+# and an error message on stderr.
 #
 has_command_python3=0;
 has_command_pip3=0;
 has_command_git=0;
-if command -v "python3"  > "/dev/null"; then has_command_python3=1;     fi
-if command -v "pip3"     > "/dev/null"; then has_command_pip3=1;        fi
-if command -v "git"      > "/dev/null"; then has_command_git=1;         fi
+has_command_sshd=0;
+has_ssh_key=0;
+has_ssh_nopwd=0;
+if command -v "python3"  > "/dev/null"; then has_command_python3=1;  fi
+if command -v "pip3"     > "/dev/null"; then has_command_pip3=1;     fi
+if command -v "git"      > "/dev/null"; then has_command_git=1;      fi
+if command -v "sshd"     > "/dev/null"; then has_command_sshd=1;     fi
+if [ -f ~/.ssh/id_rsa.pub ];            then has_ssh_key=1;          fi
+if ! ssh -o BatchMode=yes localhost exit 2 > "/dev/null";
+                                        then has_ssh_nopwd=1;        fi
 if [ ${has_command_python3} -eq 0 ]; then
     printf "The 'python3' command was not found.\n"                     1>&2;
     printf "Try installing python3 with:\n"                             1>&2;
@@ -92,6 +105,25 @@ if [ ${has_command_git} -eq 0 ]; then
     printf "Try installing git with:\n"                                 1>&2;
     printf "   sudo apt-get update\n"                                   1>&2;
     printf "   sudo apt-get install git\n"                              1>&2;
+    exit 1;
+fi
+if [ ${has_command_sshd} -eq 0 ]; then
+    printf "The 'ssh' service was not found.\n"                         1>&2;
+    printf "Try installing ssh with:\n"                                 1>&2;
+    printf "   sudo apt-get update\n"                                   1>&2;
+    printf "   sudo apt-get install openssh-server\n"                   1>&2;
+    exit 1;
+fi
+if [ ${has_ssh_key} -eq 0 ]; then
+    printf "A public key was not found at ~/.ssh/id_rsa.pub.\n"         1>&2;
+    printf "Try creating one with:\n"                                   1>&2;
+    printf "   ssh-keygen -t rsa\n"                                     1>&2;
+    exit 1;
+fi
+if [ ${has_ssh_nopwd} -eq 0 ]; then
+    printf "Passwordless SSH to localhost was not configured.\n"        1>&2;
+    printf "Try configuring it with:\n"                                 1>&2;
+    printf "   ssh-copy-id ${USER}@localhost\n"                         1>&2;
     exit 1;
 fi
 
@@ -269,5 +301,15 @@ fi
 # and then passed to the click library to use as
 # the name of the command in the help string.
 #
+# We try to support both bash and zsh here.
+#
 NAME_APP=$(basename "$0")
-python3 -m da.cli.command "${NAME_APP}" "${@}"
+if (( ${#} != 0 )); then
+    if [[ $SHELL == *"/zsh"* ]]; then
+        python3 -m da.cli.command "${NAME_APP}" "${@[@]}"
+    else
+        python3 -m da.cli.command "${NAME_APP}" "${@}"
+    fi
+else
+    python3 -m da.cli.command "${NAME_APP}"
+fi
